### ISSUE TITLE
about random crashes

### ISSUE THREAD

**Issue by NeoCharmy** [GdGohan/SonicRacingTransformedAndroidUpdate-NewVersion#3]
Hi, I've completed full game, with all 80 levels + 3 last GPs, (DLC) & I've just figured it out that, all of the random crashes ONLY happens on the stages which includes water/lava.
I've also tried with vanilla obb but the result was same.
my device: poco x3 gt (mali)
No vm
& with this version:
https://drive.google.com/file/d/1rQ1PjeFbIQk4Vdl_fZtnRfJiQ-eAhUc0/view
I've also tried it on some other devices like A11 & it was also same (I've only played first WT on them)
btw I'm a big fan of this project 
Idk about codding but I wish I could help about any possible thing in here

**Comment by GdGohan** [comment]
and v4b?

**Comment by NeoCharmy** [comment]
oh, I thought that was just a beta but that's actually an stable update (since I've also tried some of others but they did crash at first)
It fixed now
(still there's some random crashes happen a bit after that all stars button disappears for no reason just like how it was on those days with original version. but it's too rare to crash now so it doesn't really matter)
